In [1]:
import numpy as np

In [5]:
%%time
# pthon trick
a = list(range(1,10000000))
a

CPU times: user 195 ms, sys: 127 ms, total: 322 ms
Wall time: 327 ms


[1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 107,
 108,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 166,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185

In [4]:
%%time
# generate 10 Million numbers with numpy code
a = np.arange(1,10000000)

CPU times: user 19.7 ms, sys: 139 ms, total: 159 ms
Wall time: 160 ms


In [5]:
160/327

0.4892966360856269

# documentation code

In [11]:
a = np.arange(6)
a1 = a[np.newaxis,]
print(a.shape)
print(a1.shape)

(6,)
(1, 6)


In [13]:
a = np.array(1)
a.ndim

0

In [18]:
a = np.array([1,3,2])
print(a[2])
a.ndim

2


1

In [15]:
a = np.array([[1,3,2],
             [3,4,5]])
a.ndim

2

In [17]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print(a.ndim)
a[0]

2


array([1, 2, 3, 4])

In [20]:
a = np.array([[1, 2, 3, 4], 
              [5, 6, 7, 8], 
              [9, 10, 11, 12]])
print(a[0])
print(a[0][3])

[1 2 3 4]
4


# How to create a basic array

### This section covers 
* np.array(), np.zeros(), np.ones(), np.empty(), np.arange(), np.linspace(), dtype


In [24]:
a = np.array(1) # number
print(type(a))

a = np.array([1,2,3]) #list
print(type(a))

a = np.array((1,2,3)) #tuple
print(type(a))

b = np.array(a) #array
print(type(b))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [25]:
a = np.zeros(2)
a

array([0., 0.])

In [26]:
a = np.zeros(5)
a

array([0., 0., 0., 0., 0.])

In [30]:
a = np.zeros((10,10))
a

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
a = np.ones((10,10))
a

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [1]:
np.empty(2)

NameError: name 'np' is not defined

In [35]:
np.arange(2,21,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [43]:
np.linspace(1,2,5) # last argument number of steps

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [46]:
a = np.ones((10,10), dtype=np.int64)
a

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [47]:
rr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
rr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [50]:
%%time
sorted(rr)

CPU times: user 28 µs, sys: 7 µs, total: 35 µs
Wall time: 40.3 µs


[1, 2, 3, 4, 5, 6, 7, 8]

In [51]:
%%time
np.sort(rr)

CPU times: user 35 µs, sys: 9 µs, total: 44 µs
Wall time: 35 µs


array([1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
rr = np.array([2, 1, 5, 3, 7, 4, 6, 8])
np.argsort(rr)# return index according to your data sorting numbers

array([1, 0, 3, 5, 2, 6, 4, 7])

In [53]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
np.concatenate((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [55]:
a = np.ones((10,10))
b = np.ones((10,10)) + 1

np.concatenate((a,b))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.]])

In [57]:
x = np.array([[1, 2], [3, 4]])
y = np.array([[5, 6]])

print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]]


In [58]:
np.concatenate((x,y), axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [62]:
x = np.array([[1, 2], 
              [3, 4]])
y = np.array([[5, 6],
              [7,8]])
print(x)
print(y)

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]


In [61]:
np.concatenate((x,y), axis=1)

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

# How do you know the shape and size of an array?

In [64]:
a = np.arange(1,101).reshape(10,10)
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [65]:
a.ndim

2

In [67]:
a.size # total elements counts

100

In [68]:
    a.shape

(10, 10)

In [72]:
b = np.arange(1,11).reshape((2,5)) # (5,2) (10,1), (1,10)
b

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [77]:
b = np.arange(1,28).reshape(3,9)
b = np.arange(1,28).reshape(9,3)
# b = np.arange(1,28).reshape(3,3,3)
b

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24],
       [25, 26, 27]])

# Slicing

In [82]:
data = np.array([1, 2, 3])
data[1]

2

In [86]:
data = np.arange(1,11)
print(data)
print(data[3:])# --> left to right
print(data[-5:])# --> left to right


[ 1  2  3  4  5  6  7  8  9 10]
[ 4  5  6  7  8  9 10]
[ 6  7  8  9 10]


In [90]:
# if we passed same dimension array filled with True and False 
#so it return only True indexes numbers/elements

data = np.arange(1,11)
print(data)
data[[False,False,False,True,False,False,True,False,False,False]] 



[ 1  2  3  4  5  6  7  8  9 10]


array([4, 7])

In [98]:
a = np.random.randint(0,255, size=(5,5))
a

array([[252, 187,   8, 117,  17],
       [206, 197,  58, 222,  79],
       [ 10, 228, 164,  99, 182],
       [200, 148,  73, 193,  10],
       [  0,  77,   3, 204,  74]])

In [99]:
a<=10

array([[False, False,  True, False, False],
       [False, False, False, False, False],
       [ True, False, False, False, False],
       [False, False, False, False,  True],
       [ True, False,  True, False, False]])

In [106]:
# fancy slicing
a[[[False, False,  True, False, False], [False, False, False, False, False],  [ True, False, False, False, False],  [False, False, False, False,  True],[ True, False,  True, False, False]]]

/home/mqasim/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.
  """Entry point for launching an IPython kernel.


IndexError: too many indices for array: array is 2-dimensional, but 5 were indexed

In [107]:
a[a <= 10]

array([ 8, 10, 10,  0,  3])

In [108]:
a = np.random.randint(0,255, size=(10,10))
a

array([[238, 123, 142, 117, 103, 200, 141,  53,  72, 158],
       [226,  43, 119, 249, 247, 142, 187,  57, 169,  28],
       [234, 103,   9, 198, 157, 173,  39,  22, 209,  81],
       [ 80, 105, 146,  37,  72, 252, 248, 244, 197, 120],
       [224,   7, 246, 129, 153,  76,  58, 252, 228, 162],
       [226,  25, 209,  82,  65,  44, 165, 176, 137,  78],
       [219, 215, 169,  96, 239, 112, 170,  78, 210,  36],
       [206, 164, 218,   3,  16,   9,  17, 247,  43, 142],
       [209, 246, 242,  96, 136, 194,  52,  82, 156, 137],
       [172,  26,  69,  12, 144, 116,  80, 228, 109, 224]])

In [112]:
a[(a % 3) == 0]

array([123, 117, 141,  72, 249,  57, 234,   9, 198,  39,  81, 105,  72,
       252, 120, 246, 129, 153, 252, 228, 162, 165,  78, 219,  96,  78,
       210,  36,   3,   9, 246,  96, 156,  69,  12, 144, 228])

In [2]:
a  = np.array([1,  2,  3,  4,  5,  6,  7,  8,  9, 10])
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
a1 = np.array([[1, 1],
               [2, 2]])
a2 = np.array([[3, 3],
               [4, 4]])

np.vstack((a1,a2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [4]:
np.hstack((a1,a2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [5]:
a = np.hstack((a1,a2))
a

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

In [7]:
np.hsplit(a, 2)

[array([[1, 1],
        [2, 2]]),
 array([[3, 3],
        [4, 4]])]

In [8]:
np.vsplit(a, 2)

[array([[1, 1, 3, 3]]), array([[2, 2, 4, 4]])]

In [12]:
a = np.arange(1,101).reshape((10,10))
print(a)
print(a[5:,5:])
a[5:,5:] += 20
print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
[[ 56  57  58  59  60]
 [ 66  67  68  69  70]
 [ 76  77  78  79  80]
 [ 86  87  88  89  90]
 [ 96  97  98  99 100]]
[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  76  77  78  79  80]
 [ 61  62  63  64  65  86  87  88  89  90]
 [ 71  72  73  74  75  96  97  98  99 100]
 [ 81  82  83  84  85 106 107 108 109 110]
 [ 91  92  93  94  95 116 117 118 119 120]]


# Basic array operations

In [13]:
a = [1,2,3,4,6]

a = [i+5 for i in a]    
a

[6, 7, 8, 9, 11]

In [14]:
a = [1,2,3,4,6]

for idx,num in enumerate(a):
    a[idx] = num + 5
a

[6, 7, 8, 9, 11]

In [15]:
a = np.array([1,2,3,4,6])

a + 5

array([ 6,  7,  8,  9, 11])

In [ ]:
a = np.array([1,2,3,4,6])
             [5,5,5,5,5]
    
# Broad Casting

In [16]:
a = np.arange(1,28).reshape((3,3,3))
a 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [18]:
a * 2 

array([[[ 2,  4,  6],
        [ 8, 10, 12],
        [14, 16, 18]],

       [[20, 22, 24],
        [26, 28, 30],
        [32, 34, 36]],

       [[38, 40, 42],
        [44, 46, 48],
        [50, 52, 54]]])

In [19]:
a = np.arange(1,101).reshape((10,10))
a

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [20]:
a.sum()

5050

In [21]:
a.sum(axis=0)

array([460, 470, 480, 490, 500, 510, 520, 530, 540, 550])

In [22]:
a.sum(axis=1)

array([ 55, 155, 255, 355, 455, 555, 655, 755, 855, 955])

In [23]:
    a = np.arange(1,28).reshape((3,3,3))
a 

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [24]:
a.sum(axis=2)

array([[ 6, 15, 24],
       [33, 42, 51],
       [60, 69, 78]])

In [25]:
a = np.arange(1,28).reshape((3,9))
a 

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24, 25, 26, 27]])

In [27]:
a = np.arange(1,28).reshape((3,9))
print(a)
a.min()

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


1

In [28]:
a = np.arange(1,28).reshape((3,9))
print(a)
a.min(axis=0)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a = np.arange(1,28).reshape((3,9))
print(a)
a.min(axis=1)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


array([ 1, 10, 19])

In [30]:
a = np.arange(1,28).reshape((3,9))
print(a)
a.max(axis=1)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


array([ 9, 18, 27])

In [31]:
a = np.arange(1,28).reshape((3,9))
print(a)
a.mean(axis=1)

[[ 1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18]
 [19 20 21 22 23 24 25 26 27]]


array([ 5., 14., 23.])

In [ ]:
AI-46165

# Attendance

In [43]:
import re

f = open("./meeting_saved_chat.txt")
f = f.readlines()
f = [re.findall("\d{5}",i) for i in f]

student_list  = []
for i in f:
    if len(i)>=1:
        if i[0] not in student_list:
            student_list.append(i[0])
            
print(len(student_list))
student_list            

25


['47134',
 '49551',
 '45055',
 '44226',
 '46190',
 '40504',
 '46165',
 '40352',
 '40222',
 '42612',
 '40969',
 '40591',
 '51851',
 '40200',
 '46214',
 '50908',
 '40483',
 '41824',
 '47456',
 '43688',
 '45939',
 '46716',
 '44378',
 '43619',
 '43505']